version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
